package EtcProgram;

import LogIn.SignUpWindow;
import EtcProgram.ChangePasswordWindow;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import ClassMethod.DB_Con;
import LogIn.SignUpWindow;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author PIPHAT
 */
public class NewPasswordForChangePasswordWindow extends javax.swing.JFrame {

    /**
     * Creates new form NewPasswordWindow
     */
    public NewPasswordForChangePasswordWindow() {
        initComponents();
        NewPass.requestFocus();
    }

    public boolean isEnglish(String alphabet) {
        String eng1 = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        int engnum = 0;
        for (int i = 0; i < alphabet.length(); i++) {
            for (int j = 0; j < eng1.length(); j++) {
                if (alphabet.charAt(i) == eng1.charAt(j)) {
                    engnum++;
                }
            }
        }
        if (engnum == alphabet.length()) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NewPass = new javax.swing.JTextField();
        CNewPass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Angsana New", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("รหัสผ่านใหม่");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 48, -1, -1));

        jLabel4.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("รหัสผ่าน");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 124, -1, -1));

        NewPass.setColumns(256);
        NewPass.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        NewPass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        NewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewPassActionPerformed(evt);
            }
        });
        getContentPane().add(NewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 121, 150, -1));

        CNewPass.setColumns(256);
        CNewPass.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        CNewPass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(CNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 161, 150, -1));

        jLabel1.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("ยืนยันรหัสผ่าน");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 161, -1, -1));

        Submit.setBackground(new java.awt.Color(255, 255, 255));
        Submit.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        Submit.setIcon(new javax.swing.ImageIcon("C:\\My Learing\\Java\\DIT102\\GachaProgram\\photo\\Ok.png")); // NOI18N
        Submit.setText("ตกลง");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 206, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\My Learing\\Java\\DIT102\\GachaProgram\\photo\\Back.jpg")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 38, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\My Learing\\Java\\DIT102\\GachaProgram\\photo\\Change Cat.gif")); // NOI18N
        jLabel5.setText("sadasdasd");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SignUpWindow SUW = new SignUpWindow();
        this.dispose();
        SUW.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        ImageIcon Cat_Warning = new ImageIcon("C://My Learing//Java//DIT102//GachaProgram//photo//Cat Warning.gif");
        DB_Con db = new DB_Con();
        try {
            String NPass = NewPass.getText();
            String CNPass = CNewPass.getText();
            String sql = String.format("Update user set user_password = '%s' Where user_id = '%s' ", NPass, ChangePasswordWindow.get_id());
            if (isEnglish(NPass)&&NPass.length() < 8||NPass.length() >16&&NPass.equals(CNPass)) {
                JOptionPane.showMessageDialog(null, "Please input 8-16 characters and Use only English and Numeric!", "", JOptionPane.INFORMATION_MESSAGE, Cat_Warning);
            } else { 
                    {
                        if (db.execute(sql)) {
                            ImageIcon Cat = new ImageIcon("C://My Learing//Java//DIT102//GachaProgram//photo//Cat Success.gif");
                            JOptionPane.showMessageDialog(null, "Success!", "", JOptionPane.INFORMATION_MESSAGE, Cat);
                            SignUpWindow SUW = new SignUpWindow();
                            this.dispose();
                            SUW.setVisible(true);
                        }
                    }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Something was Wrong!", "", JOptionPane.INFORMATION_MESSAGE, Cat_Warning);
        }
    }//GEN-LAST:event_SubmitActionPerformed

    private void NewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPasswordForChangePasswordWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPasswordForChangePasswordWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPasswordForChangePasswordWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPasswordForChangePasswordWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewPasswordForChangePasswordWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CNewPass;
    private javax.swing.JTextField NewPass;
    private javax.swing.JButton Submit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
