package EtcProgram;

import LogIn.LoginWindow;
import java.sql.ResultSet;
import ClassMethod.DB_Con;
import LogIn.LoginWindow;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author PIPHAT
 */
public class RegisterWindow extends javax.swing.JFrame {

    /**
     * Creates new form RegisterWindow
     */
    public RegisterWindow() {
        initComponents();
        ID.requestFocus();
    }

    public boolean isEnglish(String alphabet) {
        String eng1 = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        int engnum = 0;
        for (int i = 0; i < alphabet.length(); i++) {
            for (int j = 0; j < eng1.length(); j++) {
                if (alphabet.charAt(i) == eng1.charAt(j)) {
                    engnum++;
                }
            }
        }
        if (engnum == alphabet.length()) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Please use only Alphabet and Numeric!", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
    }

    public boolean isNumeric(String numeric) {
        try {
            int n1 = Integer.parseInt(numeric);
            return true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please input your Telephone Number!", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
    }

    public boolean isEmail(String email) {
        boolean a = false, b = false;
        for (int i = 0; i < email.length(); i++) {
            if (email.charAt(i) == '@') {
                a = true;
            }
            if (email.charAt(i) == '.') {
                b = true;
            }
        }
        if (a && b) {
            email = email.replace("@", "");
            email = email.replace(".", "");
            if (isEnglish(email)) {
                return true;
            } else {
                JOptionPane.showMessageDialog(this, "Please input you e-mail", "Warning", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        } else {
            return false;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        TelNum = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        ConPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLabel1.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        JLabel1.setForeground(new java.awt.Color(255, 51, 51));
        JLabel1.setText("ID");
        getContentPane().add(JLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 65, -1, -1));

        jLabel2.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("รหัสผ่าน");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 105, -1, -1));

        jLabel3.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("ยืนยันรหัสผ่าน");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 143, -1, -1));

        jLabel4.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("E-mail");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 184, -1, -1));

        jLabel5.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("เบอร์โทรศัพท์");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 229, -1, -1));

        ID.setColumns(256);
        ID.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        ID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 62, 150, -1));

        Email.setColumns(256);
        Email.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        Email.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 181, 150, -1));

        TelNum.setColumns(256);
        TelNum.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        TelNum.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(TelNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 226, 150, -1));

        Password.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        Password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 102, 150, -1));

        ConPass.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        ConPass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(ConPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 140, 150, -1));

        jLabel1.setFont(new java.awt.Font("Angsana New", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("สมัครผู้ใช้งาน");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, -1));

        Submit.setBackground(new java.awt.Color(255, 255, 255));
        Submit.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        Submit.setIcon(new javax.swing.ImageIcon("C:\\My Learing\\Java\\DIT102\\GachaProgram\\photo\\Ok.png")); // NOI18N
        Submit.setText("ตกลง");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 271, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\My Learing\\Java\\DIT102\\GachaProgram\\photo\\Back.jpg")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 39, -1));

        jLabel6.setFont(new java.awt.Font("Angsana New", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("*สามารถใช้ได้เฉพาะ A-Z,a-z และ 0-9");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 271, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\My Learing\\Java\\DIT102\\GachaProgram\\photo\\Register Cat.gif")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        ImageIcon Cat_Warning = new ImageIcon("C://My Learing//Java//DIT102//GachaProgram//photo//Cat Warning.gif");
        DB_Con db = new DB_Con();
        String Id = ID.getText();
        String Pass = Password.getText();
        String CPass = ConPass.getText();
        String Em = Email.getText();
        String TNum = TelNum.getText();
        String sql = String.format("INSERT INTO `gacha program`.`user` (user_id, user_password, user_email, user_tel)"
                + "VALUES ('%s', '%s', '%s', '%s')", Id, Pass, Em, TNum);
        String sql2 = String.format("Select user_id from user where user_id = '%s'", Id);
        if (isEnglish(Id) && isEnglish(Pass) && isEnglish(CPass) && isEmail(Em) && isNumeric(TNum) && Pass.equals(CPass)) {
            if (Id.length() < 8 || Id.length() > 16 || Pass.length() < 8 || Pass.length() > 16 || CPass.length() < 8 || CPass.length() > 16 || Em.length() < 13 || Pass.length() > 40 || TNum.length() != 10) {
                JOptionPane.showMessageDialog(null, "Please input 8-16 characters and Use only English and Numeric!", "", JOptionPane.INFORMATION_MESSAGE, Cat_Warning);
            } else {
                try {
                    ResultSet rs = db.getResultSet(sql2);
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(null, "Already Have This ID!", "", JOptionPane.INFORMATION_MESSAGE, Cat_Warning);
                    } else {
                        if (db.execute(sql)) {
                            ImageIcon Cat = new ImageIcon("C://My Learing//Java//DIT102//GachaProgram//photo//Cat Success.gif");
                            JOptionPane.showMessageDialog(null, "Success!", "", JOptionPane.INFORMATION_MESSAGE, Cat);
                            LoginWindow LW = new LoginWindow();
                            this.dispose();
                            LW.setVisible(true);
                        }
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Something was Wrong!", "", JOptionPane.INFORMATION_MESSAGE, Cat_Warning);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please input out all fields!", "", JOptionPane.INFORMATION_MESSAGE, Cat_Warning);
        }
    }//GEN-LAST:event_SubmitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LoginWindow LW = new LoginWindow();
        this.dispose();
        LW.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_IDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConPass;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField ID;
    private javax.swing.JLabel JLabel1;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton Submit;
    private javax.swing.JTextField TelNum;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
