package LogIn;

import EtcProgram.NekoGachaWindow;
import EtcProgram.ForgotPasswordWindow;
import EtcProgram.ChangePasswordWindow;
import LogIn.LoginWindow;
import ClassMethod.DB_Con;
import EtcProgram.NekoGachaWindow;
import java.sql.*;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author PIPHAT
 */
public class SignUpWindow extends javax.swing.JFrame {

    /**
     * Creates new form SIngUpWindow
     */
    public SignUpWindow() {
        initComponents();
        IdUser.requestFocus();
    }

    public static String get_id() {
        return IdUser.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IdUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ChangePass = new javax.swing.JButton();
        ForgotPass = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        PasswordUser = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IdUser.setColumns(256);
        IdUser.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        IdUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        IdUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdUserActionPerformed(evt);
            }
        });
        getContentPane().add(IdUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 160, -1));

        jLabel1.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("รหัสผ่าน");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        ChangePass.setBackground(new java.awt.Color(255, 102, 102));
        ChangePass.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        ChangePass.setText("เปลี่ยนรหัสผ่าน");
        ChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePassActionPerformed(evt);
            }
        });
        getContentPane().add(ChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        ForgotPass.setBackground(new java.awt.Color(255, 102, 102));
        ForgotPass.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        ForgotPass.setText("ลืมรหัสผ่าน");
        ForgotPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgotPassActionPerformed(evt);
            }
        });
        getContentPane().add(ForgotPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 111, -1));

        Submit.setBackground(new java.awt.Color(255, 255, 255));
        Submit.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        Submit.setIcon(new javax.swing.ImageIcon("C:\\My Learing\\Java\\DIT102\\GachaProgram\\photo\\Ok.png")); // NOI18N
        Submit.setText("ตกลง");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 90, -1));

        PasswordUser.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        PasswordUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        PasswordUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordUserKeyPressed(evt);
            }
        });
        getContentPane().add(PasswordUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 160, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\My Learing\\Java\\DIT102\\GachaProgram\\photo\\Back.jpg")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 39, -1));

        jLabel3.setFont(new java.awt.Font("Angsana New", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("เข้าสู่ระบบ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\My Learing\\Java\\DIT102\\GachaProgram\\photo\\Cat Welcome.gif")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        ImageIcon Cat = new ImageIcon("C://My Learing//Java//DIT102//GachaProgram//photo//Cat Hi.gif");
        ImageIcon Cat_Warning = new ImageIcon("C://My Learing//Java//DIT102//GachaProgram//photo//Cat Warning.gif");
        DB_Con db = new DB_Con();
        try {
            String Id = IdUser.getText();
            String Password = PasswordUser.getText();
            String sql = String.format("Select * from user Where user_id ='%s' and user_password ='%s'", Id, Password);
            ResultSet rs = db.getResultSet(sql);
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Welcome!", "", JOptionPane.INFORMATION_MESSAGE, Cat);
                NekoGachaWindow IGW = new NekoGachaWindow();
                this.setVisible(false);
                IGW.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect ID or Password!", "", JOptionPane.INFORMATION_MESSAGE, Cat_Warning);
            }
        } catch (Exception e) {
               JOptionPane.showMessageDialog(null, "Something was Wrong!", "", JOptionPane.INFORMATION_MESSAGE, Cat_Warning);
        }
    }//GEN-LAST:event_SubmitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LoginWindow LW = new LoginWindow();
        this.dispose();
        LW.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePassActionPerformed
        // TODO add your handling code here:
        ChangePasswordWindow CPW = new ChangePasswordWindow();
        this.dispose();
        CPW.setVisible(true);
    }//GEN-LAST:event_ChangePassActionPerformed

    private void ForgotPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgotPassActionPerformed
        // TODO add your handling code here:
        ForgotPasswordWindow FPW = new ForgotPasswordWindow();
        this.dispose();
        FPW.setVisible(true);
    }//GEN-LAST:event_ForgotPassActionPerformed

    private void PasswordUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordUserKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordUserKeyPressed

    private void IdUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangePass;
    private javax.swing.JButton ForgotPass;
    private static javax.swing.JTextField IdUser;
    private javax.swing.JPasswordField PasswordUser;
    private javax.swing.JButton Submit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
